Repository RWTH-EBC/AixLib, pull requests merged in 2019-11, with the labels that each got.

#762 Issue747 port heights of buffer storage
  AixLib/Airflow/FacadeVentilationUnit/Examples/FacadeVentilationUnit.mo
  AixLib/Airflow/Multizone/MediumColumnDynamic.mo
  AixLib/BoundaryConditions/WeatherData/Old/WeatherTRY/Weather.mo
  AixLib/Controls/HVACAgentBasedControl/Examples/BuildingHeatingSystems/BuildingHeating.mo
  AixLib/DataBase/Storage/BufferStorageBaseDataDefinition.mo
  AixLib/DataBase/Storage/Generic_New_2000l.mo
  AixLib/FastHVAC/Components/Storage/BaseClasses/QBuoyFunction.mo
  AixLib/FastHVAC/Components/Storage/HeatStorage.mo
  AixLib/FastHVAC/Components/Storage/HeatStorageVariablePorts.mo
  AixLib/FastHVAC/Components/Storage/StorageSimpleWall.mo
  AixLib/FastHVAC/Components/Valves/ThermostaticValve.mo
  AixLib/Fluid/Actuators/Valves/Examples/MixingValveBackwardDirection.mo
  AixLib/Fluid/Actuators/Valves/Examples/MixingValveForwardDirection.mo
  AixLib/Fluid/Actuators/Valves/ExpansionValves/BaseClasses/PartialExpansionValve.mo
  AixLib/Fluid/Actuators/Valves/ExpansionValves/BaseClasses/PartialModularExpansionVavles.mo
  AixLib/Fluid/Delays/Examples/Delay.mo
  AixLib/Fluid/Examples/GeothermalHeatPump/BaseClasses/GeothermalHeatPumpBase.mo
  AixLib/Fluid/Examples/GeothermalHeatPump/GeothermalHeatPump.mo
  AixLib/Fluid/FMI/Adaptors/ThermalZone.mo
  AixLib/Fluid/FMI/ExportContainers/Examples/FMUs/HVACZone.mo
  AixLib/Fluid/FMI/ExportContainers/Examples/FMUs/HVACZones.mo
  AixLib/Fluid/FixedResistances/Pipe.mo
  AixLib/Fluid/FixedResistances/Validation/PlugFlowPipes/Data/TestData.mo
  AixLib/Fluid/FixedResistances/Validation/PlugFlowPipes/PlugFlowULg.mo
  AixLib/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/Examples/BaseClasses/PartialBorehole.mo
  AixLib/Fluid/HeatExchangers/ActiveWalls/Distributor.mo
  AixLib/Fluid/HeatExchangers/ActiveWalls/Examples/PanelHeatingMultiple.mo
  AixLib/Fluid/HeatExchangers/BaseClasses/Examples/HANaturalCylinder.mo
  AixLib/Fluid/HeatPumps/BaseClasses/CycleHP.mo
  AixLib/Fluid/HeatPumps/BaseClasses/InnerCycle.mo
  AixLib/Fluid/HeatPumps/Examples/HeatPumpDetailed.mo
  AixLib/Fluid/HeatPumps/Examples/HeatPumpSimple.mo
  AixLib/Fluid/HeatPumps/HeatPump.mo
  AixLib/Fluid/HeatPumps/HeatPumpDetailed.mo
  AixLib/Fluid/Humidifiers/Validation/SprayAirWasher_X.mo
  AixLib/Fluid/Interfaces/Examples/HeaterCooler_u.mo
  AixLib/Fluid/Interfaces/FourPortHeatExchanger.mo
  AixLib/Fluid/MixingVolumes/BaseClasses/Validation/MixingVolumeHeatPortWater.mo
  AixLib/Fluid/MixingVolumes/Examples/HydraulicSeparator.mo
  AixLib/Fluid/Sensors/ModularSensors.mo
  AixLib/Fluid/Solar/Thermal/Examples/SolarThermalCollector.mo
  AixLib/Fluid/Storage/BaseClasses/ThirdOrderStratifier.mo
  AixLib/Fluid/Storage/BufferStorage.mo
  AixLib/Resources/Scripts/ConvertAixLib_from_0.7.11_to_0.7.12.mos
  AixLib/Systems/HeatPumpSystems/BaseClasses/HPSystemController.mo
  AixLib/Systems/HeatPumpSystems/BaseClasses/PartialHeatPumpSystem.mo
  AixLib/ThermalZones/HighOrder/Components/Walls/Wall.mo
  AixLib/ThermalZones/HighOrder/Components/WindowsDoors/WindowSimple.mo
  AixLib/ThermalZones/ReducedOrder/Multizone/BaseClasses/PartialMultizone.mo
  AixLib/ThermalZones/ReducedOrder/ThermalZone/ThermalZone.mo
  AixLib/Utilities/Psychrometrics/Examples/TWetBul_TDryBulXi.mo
  AixLib/Utilities/Sensors/ExergyMeter/StoredExergyMeter.mo
  AixLib/package.mo
Labels: enhancement

#794 issue309 - rework heat exchangers
  AixLib/FastHVAC/HeatExchangers/BaseClasses/PseudoRadiator.mo
  AixLib/FastHVAC/HeatExchangers/DHWHeatExchanger.mo
  AixLib/FastHVAC/HeatExchangers/Examples/DHWHeatExchanger/DHWHeatExchanger.mo
  AixLib/FastHVAC/HeatExchangers/Examples/MultiRadiator/ValidationMultiRadiator.mo
  AixLib/FastHVAC/HeatExchangers/MultiRadiator.mo
  AixLib/FastHVAC/Sensors/MassFlowSensor.mo
  AixLib/FastHVAC/Valves/ThreeWayValve.mo
Labels: FastHVAC

#787 Issue785 steam humidifier u
  AixLib/Fluid/Humidifiers/Examples/GenericHumidifier_u.mo
  AixLib/Fluid/Humidifiers/Examples/package.order
  AixLib/Fluid/Humidifiers/GenericHumidifier_u.mo
  AixLib/Fluid/Humidifiers/package.order
  AixLib/Resources/Scripts/Dymola/Fluid/Humidifiers/Examples/GenericHumidifier_u.mos
Labels: New Model
