Repository RWTH-EBC/AixLib, pull requests merged in 2020-11, with the labels that each got.

#1045 Fixes conversion-script for conversion from 0.10.5 to 0.10.6
  AixLib/Resources/Scripts/ConvertAixLib_from_0.10.5_to_0.10.6.mos
Labels: bug

#1036 Propagate use_C_flow and CO2Con
  AixLib/BoundaryConditions/InternalGains/CO2/CO2Balance.mo
  AixLib/ThermalZones/ReducedOrder/Examples/MultizoneMoistAirCO2.mo
  AixLib/ThermalZones/ReducedOrder/Examples/MultizoneMoistAirCO2Equipped.mo
  AixLib/ThermalZones/ReducedOrder/Multizone/MultizoneMoistAirCO2.mo
  AixLib/ThermalZones/ReducedOrder/Multizone/MultizoneMoistAirCO2Equipped.mo
  AixLib/ThermalZones/ReducedOrder/ThermalZone/BaseClasses/PartialThermalZone.mo
  AixLib/ThermalZones/ReducedOrder/ThermalZone/ThermalZoneMoistCO2AirExchange.mo
Labels: bug

#1002 Add a Reference Check for regression tests
  .gitlab-ci.yml
  AixLib/Fluid/FixedResistances/GenericPipe.mo
  AixLib/Fluid/FixedResistances/Pipe.mo
  AixLib/Media/AirIncompressible.mo
  AixLib/Resources/ReferenceResults/Dymola/AixLib_Airflow_AirHandlingUnit_Examples_AHU.txt
  AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_Actuators_Dampers_Examples_Damper.txt
  AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_FixedResistances_Examples_SimplePipe.txt
  AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_Sources_Validation_Boundary.txt
  AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_Sources_Validation_BoundaryWithX_in.txt
  AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_Sources_Validation_BoundaryWithXi_in.txt
  AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_Storage_Validation_StratifiedNonUniformInitial.txt
  AixLib/Resources/ReferenceResults/Dymola/AixLib_ThermalZones_ReducedOrder_Validation_RoomWithLatentGain.txt
  AixLib/Resources/ReferenceResults/Dymola/AixLib_ThermalZones_ReducedOrder_Validation_RoomWithoutLatentGain.txt
  bin/02_CITests/CleanUpSkripts/deploy_artifacts.py
  bin/02_CITests/SyntaxTests/StyleChecking.py
  bin/02_CITests/UnitTests/CheckPackages/validatetest.py
  bin/02_CITests/UnitTests/list_extended_models.py
  bin/02_CITests/UnitTests/reference_check.py
  bin/02_CITests/UnitTests/runUnitTests.py
  bin/03_WhiteLists/changedmodels.txt
  bin/03_WhiteLists/ref_Whitelist.txt
  bin/05_Templates/UnitTests/changed_check_model.gitlab-ci.yml
  bin/05_Templates/UnitTests/changed_regression_test.gitlab-ci.yml
  bin/05_Templates/UnitTests/changed_simulate_model.gitlab-ci.yml
  bin/05_Templates/UnitTests/check_model.gitlab-ci.yml
  bin/05_Templates/UnitTests/regression_ref_check.gitlab-ci.yml
  bin/05_Templates/UnitTests/regression_test.gitlab-ci.yml
  bin/05_Templates/UnitTests/simulate_model.gitlab-ci.yml
  bin/06_Configfiles/EOF.sh
Labels: CI, unit tests

#1057 Issue926 user guide
  AixLib/UsersGuide/Acknowledgements.mo
Labels: enhancement
