Repository RWTH-EBC/AixLib, pull requests merged in 2022-10, with the labels that each got.

#1362 1361 dpcontrolledmovers fail in open modelica
  AixLib/Fluid/Movers/DpControlledMovers/DpControlled_dp.mo
  AixLib/Fluid/Movers/DpControlledMovers/package.mo
Labels: hackday

#1357 Issue1351 membrane based enthalpy exchnager om
  AixLib/Fluid/MassExchangers/MembraneBasedEnthalpyExchangers/BaseClasses/Functions/CollisionIntegral.mo
  AixLib/Fluid/MassExchangers/MembraneBasedEnthalpyExchangers/EnthalpyExchanger.mo
Labels: OpenModelica

#1373 #1372 heatingRod OpenModelica
  AixLib/Fluid/HeatExchangers/Examples/HeatingRod.mo
Labels: hackday, OpenModelica

#1374 Issue1368 pump polynomial based om
  AixLib/Fluid/Movers/PumpsPolynomialBased/Controls/CtrlDpVarN.mo
  AixLib/Fluid/Movers/PumpsPolynomialBased/PumpHeadControlled.mo
Labels: OpenModelica

#1355 Add interval length to make simulation run in OM #1341
  AixLib/Electrical/PVSystem/Examples/ExamplePVSystem.mo
Labels: OpenModelica

#1359 issue1346 Hydraulic Modules fail in Open Modelica
  AixLib/Fluid/Movers/PumpsPolynomialBased/PumpHeadControlled.mo
  AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_Movers_PumpsPolynomialBased_Examples_PumpHeadControlled.txt
  AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_Movers_PumpsPolynomialBased_Examples_PumpSpeedControlled.txt
  AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_Movers_PumpsPolynomialBased_Examples_PumpSpeedControlledDpV.txt
  AixLib/Systems/HydraulicModules/Example/Admix.mo
  AixLib/Systems/HydraulicModules/Example/Injection.mo
  AixLib/Systems/HydraulicModules/Example/Injection2WayValve.mo
  AixLib/Systems/HydraulicModules/Example/Pump.mo
  AixLib/Systems/HydraulicModules/Example/ThrottlePump.mo
  bin/interact_CI/update_ref.txt
Labels: OpenModelica
